- include: provision.yml
  tags:
    - provision

- include: deploy.yml
  tags:
    - deploy

- include: auth-deploy.yml
  tags:
    - auth-deploy

- include: build-config.yml
  tags:
    - build-config

- include: auth-deploy-config.yml
  tags:
    - auth-deploy-config

- include: keycloak_bootstrap.yml
  tags:
    - keycloak-bootstrap

- include: keycloak-update-sso-publickey.yml
  tags:
    - keycloak-update-sso-publickey
